SELECT * FROM [dbo].[TB.CG.customers]
SELECT * FROM [dbo].[TB_CG_geolocation]
SELECT *FROM[dbo].[TB_CG_olist_orders]
SELECT * FROM [dbo].[TB_CG_olist_products]
SELECT * FROM [dbo].[TB_CG_olist_sellers]
SELECT * FROM [dbo].[TB_CG_order_items]
SELECT *FROM [dbo].[TB_CG_order_payments]
SELECT * FROM [dbo].[TB_CG_order_reviews_dataset]
SELECT * FROM [dbo].[TB_CG_product_category_name]

CREATE TABLE TB_ACT_customers
(CUSTOMER_ID NVARCHAR(150),
CUSTOMER_UNIQUE_ID NVARCHAR(150),
CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
COSTUMER_CITY NVARCHAR(100),
COSTUMER_STATE CHAR(2)
)

SELECT * FROM [dbo].[TB_ACT_CUSTOMERS]

INSERT INTO TB_ACT_CUSTOMERS
SELECT * FROM [dbo].[TB.CG.customers]

CREATE TABLE TB_ACT_geolocation
(GEOLOCATION_ZIP_CODE_PREFIX NVARCHAR(15),
GEOLOCATION_L VARCHAR(150),
GEOLOCATION_ING NVARCHAR(150),
GEOLOCATION NVARCHAR(100),
GEOLOCATION_STATE CHAR(2)
)

INSERT INTO TB_ACT_geolocation
SELECT * FROM [dbo].[TB_CG_geolocation]
SELECT * FROM [dbo].[TB_ACT_geolocation]

CREATE TABLE TB_ACT_OLIST_ORDERS
(ORDER_ID NVARCHAR (150),
CUSTOMER_ID NVARCHAR(150),
ORDER_STATUS NVARCHAR(30),
ORDER_PURCHASE_TIMESTAMP DATETIME2,
ORDER_APPROVED_AT DATETIME2,
ORDER_DELIVERED_CARRIER_DATE DATETIME2,
ORDER_DELIVERED_CUSTOMER_DATE DATETIME2,
ORDER_ESTIMATED_DELIVERY_DATE DATETIME2,
)


INSERT INTO [dbo].[TB_ACT_OLIST_ORDERS]
SELECT * FROM [dbo].[TB_CG_olist_orders]

SELECT*FROM [dbo].[TB_ACT_OLIST_ORDERS]

CREATE TABLE TB_ACT_olist_products
(PRODUCT_ID NVARCHAR(150),
PRODUCT_CATEGORY_NAME NVARCHAR(50),
PRODUCT_NAME_LENGHT INT,
PRODUCT_DESCRIPTION_LENGHT INT,
PRODUCT_PHOTOS_QTY SMALLINT,
PRODUCT_WEIGHT_G INT,
PRODUCT_LENGHT_CM INT,
PRODUCT_HEIGHT_CM INT,
PRODUCT_WIDTH_CM INT)

INSERT INTO [dbo].[TB_ACT_olist_products]
SELECT * FROM [dbo].[TB_CG_olist_products]

SELECT * FROM [dbo].[TB_ACT_olist_products]

CREATE TABLE TB_ACT_olist_sellers
(SELLER_ID NVARCHAR(150),
SELLER_ZIP_CODE_PREFIX NVARCHAR(15),
SELLER_CITY NVARCHAR(50),
SELLER_STATE CHAR(2)
)


INSERT INTO [dbo].[TB_ACT_olist_sellers]
SELECT * FROM [dbo].[TB_CG_olist_sellers]

SELECT * FROM TB_ACT_olist_sellers

CREATE TABLE TB_ACT_ORDER_ITEMS
(ORDER_ID NVARCHAR(150),
ORDER_ITEM_ID INT,
PRODUCT_ID NVARCHAR(200),
SELLER_ID NVARCHAR (150),
SHIPPING_LIMIT_DATE DATETIME2,
PRICE DECIMAL(10,2),
FREIGHT_VALUE DECIMAL(10,2)
)

INSERT INTO [dbo].[TB_ACT_ORDER_ITEMS]
SELECT * FROM [dbo].[TB_CG_order_items]
CREATE TABLE TB_ACT_ORDER_PAYMENTS
(
    ORDER_ID NVARCHAR(40),            
    PAYMENT_SEQUENTIAL SMALLINT,       
    PAYMENT_TYPE NVARCHAR(20),        
    PAYMENT_VALUE DECIMAL(10,2)       
);

INSERT INTO TB_ACT_ORDER_PAYMENTS (ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_VALUE)
SELECT ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_VALUE
FROM TB_CG_order_payments

SELECT * FROM TB_ACT_ORDER_PAYMENTS
CREATE TABLE TB_ACT_ORDER_REVIEWS_DATASET
(
    REVIEW_ID NVARCHAR(40),
    ORDER_ID NVARCHAR(40),
    REVIEW_SCORE INT,
    REVIEW_COMMENT_TITLE NVARCHAR(50),
    REVIEW_COMMENT_MESSAGE NVARCHAR(100),  
    REVIEW_CREATION_DATE DATETIME2,
    REVIEW_ANSWER_TIMESTAMP DATETIME2     
);

ALTER TABLE TB_ACT_ORDER_REVIEWS_DATASET
ALTER COLUMN REVIEW_COMMENT_MESSAGE NVARCHAR(255);
ALTER TABLE TB_ACT_ORDER_REVIEWS_DATASET
ALTER COLUMN REVIEW_COMMENT_MESSAGE NVARCHAR(MAX);

INSERT INTO [dbo].[TB_ACT_ORDER_REVIEWS_DATASET]
SELECT * FROM [dbo].[TB_CG_order_reviews_dataset]


SELECT * FROM [dbo].[TB_ACT_ORDER_REVIEWS_DATASET]

CREATE TABLE TB_ACT_PRODUCT_CATEGORY_NAME
(PRODUCT_CATEGORY_NAME NVARCHAR(40),
PRODUCT_CATEGORY_NAME_ENGLISH NVARCHAR(40)
);

ALTER TABLE TB_ACT_PRODUCT_CATEGORY_NAME
ALTER COLUMN PRODUCT_CATEGORY_NAME NVARCHAR(100);

INSERT INTO [dbo].[TB_ACT_PRODUCT_CATEGORY_NAME]
SELECT * FROM [dbo].[TB_CG_product_category_name]

SELECT * FROM [dbo].[TB_ACT_PRODUCT_CATEGORY_NAME]

UPDATE [dbo].[TB_ACT_OLIST_ORDERS] SET [ORDER_ESTIMATED_DELIVERY_DATE]= NULL
WHERE [ORDER_ESTIMATED_DELIVERY_DATE] = '';

ALTER VIEW Vw_PedidosPorCliente 
AS
SELECT O.*, C.COSTUMER_CITY, C.COSTUMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_customers] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORDER_STATUS = 'delivered';

SELECT * FROM Vw_PedidosPorCliente 

DROP VIEW IF EXISTS Vw_AvaliacoesProdutos;

CREATE VIEW Vw_AvaliacoesProdutos AS
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME_LENGHT,
    AVG(R.REVIEW_SCORE) AS AVERAGE_RATING,
    COUNT(R.REVIEW_ID) AS TOTAL_REVIEWS
FROM 
    [dbo].[TB_ACT_olist_products] AS P
INNER JOIN 
    [dbo].[TB_ACT_ORDER_REVIEWS_DATASET] AS R 
    ON R.ORDER_ID IN (SELECT ORDER_ID FROM [dbo].[TB_ACT_OLIST_ORDERS] WHERE PRODUCT_ID = P.PRODUCT_ID)
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_NAME_LENGHT;

SELECT * FROM Vw_AvaliacoesProdutos;

